# Generated by Django 3.1.3 on 2022-08-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
